version: '3'

services:
    nginx:
        container_name: gryc-nginx
        ports:
            - 127.0.0.1:8080:80
        depends_on:
            - app
        networks:
            - default

    app:
        container_name: gryc-app
        image: mapiot/gryc:latest
        env_file:
            - ./docker/app.env
        depends_on:
            - rabbitmq
            - db
            - es1
        networks:
            - default

    db:
        container_name: gryc-db
        image: mariadb:10.3.2
        env_file:
            - ./docker/db.env
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

    es1:
        container_name: gryc-es1
        build: ./docker/elasticsearch
        environment:
            - cluster.name=gryc-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es1_data:/usr/share/elasticsearch/data
        networks:
            - default

    es2:
        container_name: gryc-es2
        build: ./docker/elasticsearch
        environment:
            - cluster.name=gryc-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=es1"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es2_data:/usr/share/elasticsearch/data
        networks:
            - default

    rabbitmq:
        container_name: gryc-rabbitmq
        image: rabbitmq:3.6.12
        env_file:
            - ./docker/rabbitmq.env
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - default

volumes:
    db_data:
        driver: local
    rabbitmq_data:
        driver: local
    es1_data:
        driver: local
    es2_data:
        driver: local

networks:
    default:
