version: '2.3'

services:
    nginx:
        restart: on-failure:5
        build: ./docker/nginx/prod
        volumes:
            - app_src:/var/www/html

    app:
        restart: on-failure:5
        environment:
            - SYMFONY_ENV=prod
            - SYMFONY_DEBUG=0
        volumes:
            - app_src:/var/www/html
            - app_data:/var/www/html/files

    db:
        restart: on-failure:5

    es1:
        restart: on-failure:5

    es2:
        restart: on-failure:5

    rabbitmq:
        restart: on-failure:5

volumes:
    app_src:
        driver: local
    app_data:
        driver: local
