version: '2.3'

services:
    nginx:
        container_name: gryc-nginx
        ports:
            - 127.0.0.1:${NGINX_EXPOSED_PORT}:80
        depends_on:
            - app
        mem_limit: 64M
        networks:
            - frontend

    app:
        container_name: gryc-app
        image: mapiot/gryc:latest
        env_file:
            - .env
        depends_on:
            - redis
            - rabbitmq
            - db
            - es1
        mem_limit: 512M
        networks:
            - frontend
            - backend

    db:
        container_name: gryc-db
        image: mysql:8.0.3
        environment:
          - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
          - MYSQL_USER=${DATABASE_USER}
          - MYSQL_PASSWORD=${DATABASE_PASSWORD}
          - MYSQL_DATABASE=${DATABASE_NAME}
        volumes:
            - db_data:/var/lib/mysql
        mem_limit: 512M
        networks:
            - backend

    es1:
        container_name: gryc-es1
        build: ./docker/elasticsearch
        environment:
            - cluster.name=gryc-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es1_data:/usr/share/elasticsearch/data
        mem_limit: 1G
        networks:
            - backend

    es2:
        container_name: gryc-es2
        build: ./docker/elasticsearch
        environment:
            - cluster.name=gryc-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=es1"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es2_data:/usr/share/elasticsearch/data
        mem_limit: 1G
        networks:
            - backend

    rabbitmq:
        container_name: gryc-rabbitmq
        image: rabbitmq:3.7.0
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        mem_limit: 128M
        networks:
            - backend

    redis:
        container_name: gryc-redis
        image: redis:4.0.6
        volumes:
            - redis_data:/data
        mem_limit: 128M
        networks:
            - backend

volumes:
    db_data:
        driver: local
    rabbitmq_data:
        driver: local
    es1_data:
        driver: local
    es2_data:
        driver: local
    redis_data:
        driver: local

networks:
    frontend:
    backend:
