version: '2'

services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile-prod
        volumes:
            - app_src:/var/www/html

    app:
        environment:
            - SYMFONY_ENV=prod
        volumes:
            - app_src:/var/www/html
            - app_data:/var/www/html/files
            - app_var:/var/www/html/var

volumes:
    app_src:
        driver: local
    app_data:
        driver: local
    app_var:
        driver: local
