version: '2'

services:
    nginx:
        volumes:
            - ./docker/nginx/vhost/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ../gryc:/var/www/html

    app:
        environment:
            - SYMFONY_ENV=dev
        volumes:
            - ../gryc:/var/www/html

    db:
        ports:
            - 127.0.0.1:3308:3306

    es1:
        ports:
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

    es2:
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

    es-head:
        container_name: gryc-es-head
        image: mobz/elasticsearch-head:5
        ports:
            - 127.0.0.1:9100:9100
        networks:
            - default

    rabbitmq:
        ports:
            - 127.0.0.1:15672:15672
