version: '2'

services:
    app:
        volumes:
            - app_data:/var/www/html/files
            - app_cache:/var/www/html/var/cache
            - app_logs:/var/www/html/var/logs

volumes:
    app_data:
        driver: local
    app_cache:
        driver: local
    app_logs:
        driver: local
